# Documentation
documentation:
  - any:
    - head-branch: ['docs/*', 'document/*', 'documentation/*']
    - all:
      - changed-files:
        - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

# Bug fixes
bug:
  - head-branch: ['fix/*', 'bug/*', 'hotfix/*']

# Dependencies
dependencies:
  - any:
    - head-branch: ['deps/*', 'dependencies/*']
    - changed-files:
      - any-glob-to-any-file:
        - 'requirements.txt'
        - 'package.json'
        - 'package-lock.json'
        - 'poetry.lock'
        - 'pyproject.toml'

# Enhancements/Features
enhancement:
  - head-branch: ['feat/*', 'feature/*', 'enhance/*', 'enhancement/*']

# GitHub Actions
github_actions:
  - any:
    - head-branch: ['action/*', 'workflow/*']
    - changed-files:
      - any-glob-to-any-file:
        - '.github/workflows/**'
        - '.github/actions/**'

# Testing
test:
  - any:
    - head-branch: ['test/*']
    - changed-files:
      - any-glob-to-any-file:
        - '**/*test*.py'
        - '**/*spec*.ts'
        - '**/tests/**'

# Refactoring
refactor:
  - head-branch: ['refactor/*', 'rename/*']

# CI/CD
ci:
  - any:
    - head-branch: ['ci/*']
    - changed-files:
      - any-glob-to-any-file:
        - '.github/**'
        - 'scripts/**'
        - 'docker/**'
        - '.dockerignore'
        - 'docker-compose*.yml'
        - '.gitlab-ci.yml'
        - 'Jenkinsfile'

# Configuration
config:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.json'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.toml'
      - '**/*.ini'
      - '.env*'
