// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type EquipmentCreate = {
  title: string
  description?: string | null
  category?: string | null
}

export type EquipmentPublic = {
  title: string
  description?: string | null
  category?: string | null
  id: string
}

export type EquipmentsPublic = {
  data: Array<EquipmentPublic>
  count: number
}

export type EquipmentUpdate = {
  title?: string | null
  description?: string | null
  category?: string | null
}

export type EventCreate = {
  name: string
  description?: string | null
  start_date: string
  end_date: string
  coordinator_id: string | null
  packing_equipments?: Array<PackingEquipmentCreate> | null
  meal_options?: Array<EventMealOptionCreate> | null
}

export type EventMealOptionCreate = {
  meal_id: string
  meal_type: MealType
  day: number
  max_quantity?: number | null
}

export type EventMealOptionPublic = {
  meal_id: string
  meal_type: MealType
  day: number
  max_quantity?: number | null
  id: string
  meal: MealPublic
}

export type EventPackingList = {
  event_id: string
  event_name: string
  equipments: PackingEquipmentsPublic
}

export type EventPublic = {
  name: string
  description?: string | null
  start_date: string
  end_date: string
  coordinator_id: string | null
  id: string
  packing_equipments: Array<PackingEquipmentPublic>
  meal_options: Array<EventMealOptionPublic>
}

export type EventsPublic = {
  data: Array<EventPublic>
  count: number
}

export type EventUpdate = {
  name?: string | null
  description?: string | null
  start_date?: string | null
  end_date?: string | null
  coordinator_id: string | null
  packing_equipments?: Array<PackingEquipmentCreate> | null
  meal_options?: Array<EventMealOptionCreate> | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type MealChoice = {
  id?: string
  attendance_id: string
  event_meal_option_id: string
  quantity?: number
  notes?: string | null
}

export type MealChoiceCreate = {
  attendance_id: string
  event_meal_option_id: string
  quantity?: number
  notes?: string | null
}

export type MealChoiceUpdate = {
  event_meal_option_id?: string | null
  quantity?: number | null
  notes?: string | null
}

export type MealCreate = {
  name: string
  restaurant: string
  description?: string | null
  price?: number | null
  is_vegetarian?: boolean
  is_beef?: boolean
  calories?: number | null
}

export type MealPublic = {
  name: string
  restaurant: string
  description?: string | null
  price?: number | null
  is_vegetarian?: boolean
  is_beef?: boolean
  calories?: number | null
  id: string
}

export type MealType = "breakfast" | "lunch" | "dinner" | "snack" | "late_night"

export type MealUpdate = {
  name?: string | null
  description?: string | null
  price?: number | null
  is_vegetarian?: boolean | null
  is_beef?: boolean | null
  calories?: number | null
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PackingEquipmentCreate = {
  quantity?: number
  required?: boolean
  notes?: string | null
  equipment_id: string
}

export type PackingEquipmentPublic = {
  quantity?: number
  required?: boolean
  notes?: string | null
  equipment: EquipmentPublic
}

export type PackingEquipmentsPublic = {
  data: Array<PackingEquipmentPublic>
  count: number
}

export type RoleType = "admin" | "teacher" | "staff" | "student"

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  full_name?: string | null
  role_type?: RoleType
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  full_name?: string | null
  role_type?: RoleType
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  full_name?: string | null
  role_type?: RoleType
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type AttendanceJoinEventData = {
  eventId: string
}

export type AttendanceJoinEventResponse = Message

export type AttendanceLeaveEventData = {
  eventId: string
}

export type AttendanceLeaveEventResponse = Message

export type AttendanceGetMyEventsData = {
  limit?: number
  skip?: number
}

export type AttendanceGetMyEventsResponse = unknown

export type AttendanceGetEventPackingListData = {
  eventId: string
  limit?: number
  skip?: number
}

export type AttendanceGetEventPackingListResponse = PackingEquipmentsPublic

export type AttendanceGetMyPackingListsData = {
  limit?: number
  skip?: number
}

export type AttendanceGetMyPackingListsResponse = Array<EventPackingList>

export type EquipmentsReadEquipmentsData = {
  limit?: number
  skip?: number
}

export type EquipmentsReadEquipmentsResponse = EquipmentsPublic

export type EquipmentsCreateEquipmentData = {
  requestBody: EquipmentCreate
}

export type EquipmentsCreateEquipmentResponse = EquipmentPublic

export type EquipmentsReadEquipmentData = {
  id: string
}

export type EquipmentsReadEquipmentResponse = EquipmentPublic

export type EquipmentsUpdateEquipmentData = {
  id: string
  requestBody: EquipmentUpdate
}

export type EquipmentsUpdateEquipmentResponse = EquipmentPublic

export type EquipmentsDeleteEquipmentData = {
  id: string
}

export type EquipmentsDeleteEquipmentResponse = Message

export type EquipmentsAddPackingEquipmentData = {
  eventId: string
  requestBody: PackingEquipmentCreate
}

export type EquipmentsAddPackingEquipmentResponse = PackingEquipmentPublic

export type EquipmentsListPackingEquipmentsData = {
  eventId: string
  limit?: number
  skip?: number
}

export type EquipmentsListPackingEquipmentsResponse = PackingEquipmentsPublic

export type EquipmentsGetEventEquipmentsData = {
  eventId: string
  limit?: number
  skip?: number
}

export type EquipmentsGetEventEquipmentsResponse = PackingEquipmentsPublic

export type EventsReadEventsData = {
  limit?: number
  skip?: number
}

export type EventsReadEventsResponse = EventsPublic

export type EventsCreateEventData = {
  requestBody: EventCreate | EventUpdate
}

export type EventsCreateEventResponse = EventPublic

export type EventsReadEventData = {
  id: string
}

export type EventsReadEventResponse = EventPublic

export type EventsUpdateEventData = {
  id: string
  requestBody: EventCreate | EventUpdate
}

export type EventsUpdateEventResponse = EventPublic

export type EventsDeleteEventData = {
  id: string
}

export type EventsDeleteEventResponse = unknown

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type MealChoicesCreateMealChoiceData = {
  requestBody: MealChoiceCreate
}

export type MealChoicesCreateMealChoiceResponse = MealChoice

export type MealChoicesReadMealChoicesData = {
  attendanceId?: string | null
}

export type MealChoicesReadMealChoicesResponse = Array<MealChoice>

export type MealChoicesUpdateMealChoiceData = {
  id: string
  requestBody: MealChoiceUpdate
}

export type MealChoicesUpdateMealChoiceResponse = MealChoice

export type MealChoicesDeleteMealChoiceData = {
  id: string
}

export type MealChoicesDeleteMealChoiceResponse = unknown

export type MealsCreateMealData = {
  requestBody: MealCreate | MealUpdate
}

export type MealsCreateMealResponse = MealPublic

export type MealsReadMealsData = {
  limit?: number
  skip?: number
}

export type MealsReadMealsResponse = Array<MealPublic>

export type MealsReadMealData = {
  id: string
}

export type MealsReadMealResponse = MealPublic

export type MealsUpdateMealData = {
  id: string
  requestBody: MealCreate | MealUpdate
}

export type MealsUpdateMealResponse = MealPublic

export type MealsDeleteMealData = {
  id: string
}

export type MealsDeleteMealResponse = unknown

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
