"""add_location_to_Equipment_table

Revision ID: 2843d6180e5f
Revises: c1667b9f7824
Create Date: 2025-02-19 19:20:11.921717

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2843d6180e5f'
down_revision = 'c1667b9f7824'
branch_labels = None
depends_on = None


def upgrade():
    # First add the location column as nullable
    op.add_column('equipment', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))

    # Set default values for both location and category
    op.execute("UPDATE equipment SET location = 'Unknown' WHERE location IS NULL")
    op.execute("UPDATE equipment SET category = 'Other' WHERE category IS NULL")

    # Now make both columns not nullable
    op.alter_column('equipment', 'location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    op.alter_column('equipment', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipment', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('equipment', 'location')
    # ### end Alembic commands ###
