"""update_packingitem_add_item_relationship

Revision ID: 39cbdeeb01f5
Revises: 3bae16e5fa8f
Create Date: 2024-12-19 21:08:09.960637

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '39cbdeeb01f5'
down_revision = '3bae16e5fa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'user', ['owner_id'], ['id'])
    op.add_column('packingitem', sa.Column('required', sa.Boolean(), nullable=False))
    op.add_column('packingitem', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('packingitem', sa.Column('item_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'packingitem', 'item', ['item_id'], ['id'])
    op.drop_column('packingitem', 'item_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packingitem', sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'packingitem', type_='foreignkey')
    op.drop_column('packingitem', 'item_id')
    op.drop_column('packingitem', 'notes')
    op.drop_column('packingitem', 'required')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('item', 'category')
    # ### end Alembic commands ###
