"""Add course template model

Revision ID: 4c5b53ddb0ad
Revises: 2843d6180e5f
Create Date: 2025-04-02 02:40:17.469681

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c5b53ddb0ad'
down_revision = '2843d6180e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursetemplate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('time_required', sa.Float(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coursetemplateequipmentlink',
    sa.Column('course_template_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['course_template_id'], ['coursetemplate.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('course_template_id', 'equipment_id')
    )
    op.drop_table('course')
    op.add_column('equipment', sa.Column('course_template_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'equipment', 'coursetemplate', ['course_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'course_template_id')
    op.create_table('course',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='course_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='course_pkey')
    )
    op.drop_table('coursetemplateequipmentlink')
    op.drop_table('coursetemplate')
    # ### end Alembic commands ###
