"""add_meal_tables

Revision ID: 866b1931ec70
Revises: 39cbdeeb01f5
Create Date: 2025-01-02 16:09:39.095678

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '866b1931ec70'
down_revision = '39cbdeeb01f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventmealoption',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('meal_id', sa.Uuid(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', 'LATE_NIGHT', name='mealtype'), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('meal', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('meal', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('meal', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('meal', sa.Column('is_vegetarian', sa.Boolean(), nullable=False))
    op.add_column('meal', sa.Column('is_beef', sa.Boolean(), nullable=False))
    op.add_column('meal', sa.Column('calories', sa.Integer(), nullable=True))
    op.add_column('meal', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('meal', sa.Column('created_by_id', sa.Uuid(), nullable=False))
    op.drop_constraint('meal_event_id_fkey', 'meal', type_='foreignkey')
    op.create_foreign_key(None, 'meal', 'user', ['created_by_id'], ['id'])
    op.drop_column('meal', 'meal_option')
    op.drop_column('meal', 'meal_time')
    op.drop_column('meal', 'event_id')
    op.add_column('mealchoice', sa.Column('event_meal_option_id', sa.Uuid(), nullable=False))
    op.add_column('mealchoice', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mealchoice', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('mealchoice', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint('mealchoice_meal_id_fkey', 'mealchoice', type_='foreignkey')
    op.create_foreign_key(None, 'mealchoice', 'eventmealoption', ['event_meal_option_id'], ['id'])
    op.drop_column('mealchoice', 'meal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mealchoice', sa.Column('meal_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mealchoice', type_='foreignkey')
    op.create_foreign_key('mealchoice_meal_id_fkey', 'mealchoice', 'meal', ['meal_id'], ['id'])
    op.drop_column('mealchoice', 'updated_at')
    op.drop_column('mealchoice', 'created_at')
    op.drop_column('mealchoice', 'notes')
    op.drop_column('mealchoice', 'event_meal_option_id')
    op.add_column('meal', sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('meal', sa.Column('meal_time', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('meal', sa.Column('meal_option', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meal', type_='foreignkey')
    op.create_foreign_key('meal_event_id_fkey', 'meal', 'event', ['event_id'], ['id'])
    op.drop_column('meal', 'created_by_id')
    op.drop_column('meal', 'created_at')
    op.drop_column('meal', 'calories')
    op.drop_column('meal', 'is_beef')
    op.drop_column('meal', 'is_vegetarian')
    op.drop_column('meal', 'price')
    op.drop_column('meal', 'description')
    op.drop_column('meal', 'name')
    op.drop_table('eventmealoption')
    # ### end Alembic commands ###
