"""add_meal_restaurant_name_remove_mealchoice_createtime

Revision ID: c1667b9f7824
Revises: 2928fef81424
Create Date: 2025-02-18 16:02:00.826016

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1667b9f7824'
down_revision = '2928fef81424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('restaurant', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('meal_created_by_id_fkey', 'meal', type_='foreignkey')
    op.drop_column('meal', 'created_by_id')
    op.drop_column('meal', 'created_at')
    op.drop_column('mealchoice', 'created_at')
    op.drop_column('mealchoice', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mealchoice', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('mealchoice', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('meal', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('meal', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('meal_created_by_id_fkey', 'meal', 'user', ['created_by_id'], ['id'])
    op.drop_column('meal', 'restaurant')
    # ### end Alembic commands ###
